layout_spectrum: 0.9505734
color:
  saturation: 0.1537734
  lightness: 0.8114988
  brandStrength: 0.9342327
  brandColors:
    - '#B9DBE7'
    - '#2A495D'
    - '#9CC5D9'
    - '#80A9BD'
    - '#7095A8'
  rhythmicContrast: 0.2381072
typography_spectrum: 0.5779552
name: Lostpodenco
