layout_spectrum: 0.1804384
color:
  saturation: 0.2057336
  lightness: 0.8305228
  brandStrength: 0.9342327
  brandColors:
    - '#BDD7E6'
    - '#B4AC97'
    - '#4B4840'
    - '#A26636'
    - '#30180A'
  rhythmicContrast: 0.7470489
typography_spectrum: 0.2141653
name: lostpodencomusic
